### ISSUE TITLE
Figure out better way of handling command configs

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#11]
Currently command configs aren't being handled great. This needs to be changed so that the bot can easily be deployed and used across multiple servers and use different settings.

## Subtasks
- [ ] Research and plan a way to implement this change
- [ ] Implement the command configs for different servers
- [ ] Test these changes to make sure they work

## Outcomes
- [ ] Configs can be set differently for each server
- [ ] Configs can be changed without having to restart the bot

## Blocked by
- #23

**Comment by Vylpes** [comment]
Blocked by #23

**Comment by Vylpes** [comment]
Closing now as this was mainly a research task, issues have been created to further continue this
