### ISSUE TITLE
Add verification system (can be turned on and off)

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#111]
# Description
I want to be able to add a verification system, similar to the one implemented in the MankBot. This verification system should be off by default and then have an option to set it up (maybe in the setup command, `v!config verification set on`).

# Acceptance Criteria
- [x] Scenario 1
AS a moderator
WHEN I run `v!config verification set on`
THEN this should be saved

- [x] Scenario 2
AS a moderator
WHEN I run `v!config verification set off`
THEN this should be saved

- [x] Scenario 3
AS a moderator
WHEN I run `v!config verification.channel set <name>`
THEN this should be saved

- [x] Scenario 4
AS a moderator
WHEN I run `v!config verification.role set <name>`
THEN this should be saved

- [x] Scenario 5
AS a user
WHEN I join the server
AND the verification is set on
AND I type in the code into the entry channel
THEN the bot should assign me the entry role

- [x] Scenario 6
AS a moderator
WHEN I run `v!config verification.code set <code>`
THEN this should be saved

- [x] Scenario 7
AS a moderator
WHEN I run `v!code randomise`
THEN this should save a random code

- [x] Scenario 8
AS a moderator
WHEN I run `v!code embed`
THEN the bot should respond with an embed with the current code in it

# Subtasks
- [x] Add `verification off/on` setting
- [x] Add `verification.channel` setting
- [x] Add `verification.role` setting
- [x] Add `verification.code` setting
- [x] Randomise `verification.code`
- [x] Add `verification.code` to an embed
- [x] Assign user `verification.role` if `verification.code` is the same
