### ISSUE TITLE
Add lobby entity to database

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#120]
I WANT to be able to save the lobby channels in its own entity
SO THAT its easier to maintain and manage

## Notes
- It will have the columns; Id, ChannelId, RoleId, Cooldown, LastUsed

## Subtasks
- [x] Create lobby entity
- [x] Get lobby command to use the new entity
- [x] Remove legacy code from the config command
