### ISSUE TITLE
Steal emoji command

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#128]
The ability to copy and emoji from an input and add it to the current server
SO THAT the users in the current server can use it.

## Acceptance Criteria
AS a moderator
GIVEN I want to add an emoji to the current server
WHEN I type the steal command with the name and custom emoji
THEN it should add the emoji to the current server with the name specified

AS a moderator
GIVEN I want to add an emoji to the current server
WHEN i type the steal command with the name and **LINK TO** the custom emoji
THEN it should add the emoji to the current server with the name specified

AS a user
WHEN I try to use the command
THEN I should not be allowed

## Subtasks
- [ ] Add command help
- [ ] Add steal with emoji
- [ ] Add steal with URL
