### ISSUE TITLE
Role Command: Cannot read properties of undefined

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#137]
When running the role command it crashes the bot due to not being able to find the roles in the config.

```bash
(node:15667) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/home/vylpes/projects/vylbot-app/dist/commands/role.js:25
            const roles = process.env.COMMANDS_ROLE_ROLES.split(',');
                                                          ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Role.<anonymous> (/home/vylpes/projects/vylbot-app/dist/commands/role.js:25:59)
    at Generator.next (<anonymous>)
    at /home/vylpes/projects/vylbot-app/dist/commands/role.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/vylpes/projects/vylbot-app/dist/commands/role.js:4:12)
    at Role.execute (/home/vylpes/projects/vylbot-app/dist/commands/role.js:24:16)
    at Util.<anonymous> (/home/vylpes/projects/vylbot-app/dist/client/util.js:79:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vylpes/projects/vylbot-app/dist/client/util.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Subtasks
- [x] Fix issue with bot crashing
- [x] Fix issue with it not fetching the server's prefix
- [x] Add easy way to configure
