### ISSUE TITLE
AS a user I should be able to list the moons I have obtained

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#195]
AS a user I should be able to list the moons I have obtained
SO THAT I know what ones I have

## Acceptance Criteria
AS a user
GIVEN I have the permissions
WHEN I run `/moons list`
THEN I should see a list of moons I have obtained
AND I should see a total

## Notes
- The data this should give me is: ID, Name
- This should be paginated if possible
- The entity should have: ID, Name, ServerId, UserId

## Subtasks
- [ ] Create OdysseyMoons database entity
- [ ] Create list command
- [ ] Paginate the command result
