### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#23]
I would like to migrate my bot to TypeScript. This will require a full rewrite of the project.

## Subtasks
- [x] Install and Setup TypeScript
- [x] Main bot file
- [x] Migrate commands
- [x] Migrate events
- [x] Migrate bunny command

## Outcomes
- [x] The app will be be completely rewritten in TypeScript

## Blocked by
- Vylpes/random-bunny#20

## Blocks
- #11
- #16

**Comment by Vylpes** [comment]
The v!bunny command requires https://github.com/Vylpes/random-bunny/issues/20 to be resolved. So this task can't be completed until then
