### ISSUE TITLE
Emoji hunting and battle system

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#406]
- [ ] Hunt command
- [ ] Zoo command
- [ ] Sacrifice emojis
- [ ] Add emoji to team
- [ ] Remove emoji from team
- [ ] View team
- [ ] Rename team
- [ ] Rename team member
- [ ] Battle command
- [ ] Daily command
