### ISSUE TITLE
AS a user I should be able to list the moons I have obtained

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#429]
AS a user I should be able to list the moons I have obtained
SO THAT I know what ones I have

## Acceptance Criteria
AS a user
GIVEN I have the permissions
WHEN I run `/moons list`
THEN I should see a list of moons I have obtained
AND I should see a total

## Notes
- The data this should give me is: ID, Name
- This should be paginated if possible
- The entity should have: ID, Name, ServerId, UserId

## Subtasks
- [x] Create OdysseyMoons database entity
- [x] Create list command
- [x] Paginate the command result
    - [x] Add buttons
    - [x] Add button event functionality
    - [x] Add inventory button event
- [x] Add ability to set custom user
- [x] Update tests
- [x] Resolve PR issues
- [x] Remove `MoonValues` and just use it directly
- [x] Page next button just says interaction failed and no logs
- [x] Add `WhenArchived` to the table
- [x] Moon count always says 2 not the actual number
- [x] Moon count should have the page number on it
- [ ] Add dropdown to the pagination to quickly navigate
- [ ] Order by descending
