### ISSUE TITLE
AS a user, I want the bot to be able to watch rss feeds and send new entries to a channel

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#434]
AS a user, I want the bot to be able to watch rss feeds and send new entries to a channel
SO THAT I can have the bot auto post news, etc. on an rss update

## Acceptance Criteria
AS a moderator
GIVEN I add an rss link to a configuration
WHEN the bot scans the given links
THEN the bot will post these to a specific channel

AS a moderator
GIVEN I want to add an rss link to a channel
WHEN I run `/rss add <name> <link> <channel>`
THEN the bot will add this link to the database

AS a moderator
GIVEN I want to remove an rss link from a channel
WHEN I run `/rss remove <name>`
THEN the bot will remove this link from the database

## Subtasks
- [ ] Add rss feed database table
- [ ] Add `/rss add` command
- [ ] Add `/rss remove` command
- [ ] Auto fetch RSS every x interval
- [ ] Update tests

## Notes
- The fetch interval should be configurable globally

**Comment by Vylpes** [comment]
Need to investigate how to do this
