### ISSUE TITLE
AS a potato talk moderator, I want to be able to manage another user's objectives

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#442]
AS a potato talk moderator, I want to be able to manage another user's objectives
SO THAT I can moderate the objectives of my members

## Acceptance Criteria
AS a potato talk moderator
GIVEN I want to take action on behalf of another user's objective
WHEN I run `/objectives listuser <user>`
THEN I should be able to see all objectives for `<user>`

AS a potato talk moderator
GIVEN I want to take action on behalf of another user's objective
WHEN I run `/objectives view <id>`
THEN I should be able to view another user's objective

AS a potato talk moderator
GIVEN I want to take action on behalf of another user's objective
AND I have the view embed
WHEN I click on the manage buttons
THEN I should be able to do these on behalf of them

## Subtasks
- [ ] Add `/objectives listuser` moderator command
- [ ] Allow moderators to view another user's objective
- [ ] Allow moderators to use the buttons on another user's objective
- [ ] Update tests
