### ISSUE TITLE
AS a moderator, I want to be able to manually set a user's moon count

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#446]
AS a moderator, I want to be able to manually set a user's moon count
SO THAT I can moderate a user who's misusing the command

## Acceptance Criteria
AS a moderator
GIVEN there is a user's moon count which I need to correct
WHEN I run `/moonset <user> <count>`
THEN the moon count for `<user>` should be set to `<count>`

## Subtasks
- [x] Update moon count to be a setting
- [x] Fix sql
- [x] Update new and list commands to use moon count user setting
- [x] Update new command to use the total moons
- [x] Create moonset command
- [x] Plan tests
- [ ] Update tests
