### ISSUE TITLE
Ignore channels list when logging

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#49]
This should be customisable per server. When a server has a channel in the list then the bot should not log anything for activity in that channel

## Subtasks
- [x] Add entity
- [x] Create ignore command for current channel toggle
- [x] Create ignore command for another channel toggle
- [x] Get events to ignore
