### ISSUE TITLE
Add different commands per server

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#66]
## Description
There should be a way to add custom commands that are only available for a specific server, or overwrite an existing base command.

## Acceptance Criteria
AS a bot owner
GIVEN there is no command with the same name
WHEN I add a command into a subdirectory with the name of the server id
THEN this command should only be discoverable by that server

AS a bot owner
GIVEN there is a command with the same name
WHEN I add a command into a subdirectory with the name of the server id
THEN this command should be used instead of the base command

AS a user
GIVEN there is a server exclusive command
WHEN I run the help command
THEN this command should show in its own section

AS a moderator
GIVEN I disable a server exclusive command
WHEN I run the command
THEN it should be disabled also

## Notes
- Commands folder will contain all commands for every server, eg. `commands/about.ts`
- Commands may contain a folder with the server's id for commands to override the main, eg. `commands/abc/about.ts`
- Overwritten commands without a main command will be exclusive to that server
- Overwritten commands **with** a main command will use that rather than the main command

## Subtasks
- [x] #116
- [x] Add option in register
- [x] Add server exclusive commands
- [x] Add server overwritten commands
- [x] Add needed exclusive commands
- [x] #120
- [x] Update documentation
