### ISSUE TITLE
Merge Vylbot-core into Vylbot-app

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#74]
This will allow for development to be faster as I don't need to wait to update one for the other.

## Subtasks
- [x] Merge the code
- [x] Fix events not firing
- [x] Move issues over
