### ISSUE TITLE
Add configuration helper

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#75]
This configuration helper will be used to easily fetch and save configurations for each server or for a default (not been set for a server already).

## Subtasks
- [ ] Create ability to save to database a default configuration
- [ ] Create ability to save to database a single server configuration
- [ ] Create ability to load from database, be it default if not a specific setting or the server's setting is present.
- [ ] Add cache, so prevent needing to call the database each time
- [ ] Add force update cache functionality

**Comment by Vylpes** [comment]
Already done
