### ISSUE TITLE
Save moderation events to the database

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#77]
So that you can then check the user's mod actions against them.

## Subtasks
- [x] Create database table for actions
- [x] Save moderation actions to the database
- [x] Audit command, to see the actions done against the user for this specific server
- [x] Audit clear command, to revoke an audit against a server
- [x] Audit add command, manually add one without actioning
- [x] Fix changes requested
