### ISSUE TITLE
Ability for a user to appeal an audit

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/vylbot-app#78]
This will send an alert to the mods of the server asking for an audit to be removed, this can then be either accepted or denied.

- Once denied, the user will not be able to appeal this audit again, to help stop spam

## Subtasks
- [ ] Create command
- [ ] Create event to send embed to mods
- [ ] Create buttons to accept/deny
- [ ] Revoke if accepted
- [ ] Keep and prevent again if denied
